export const generateLambeqScript = (phrase: string): string => {
    return `import warnings
warnings.filterwarnings('ignore')

from lambeq import BobcatParser
from lambeq import IQPAnsatz
from lambeq import QuantumTrainer, SPSAOptimizer
from lambeq import Dataset
import numpy as np
from pytket.circuit.display import render_circuit_jupyter
from pytket.extensions.qiskit import AerBackend

# =========================================================================
# QNLP Academic Script generated by Quantum Computer Studio v3
# Powered by Lambeq (Quantinuum) & DisCoCat
# =========================================================================

phrase = "${phrase}"

print(f"\\n[1] Parsing Phrase using Bobcat (CCG Syntax)...")
parser = BobcatParser(verbose='text')
diagram = parser.sentence2diagram(phrase)
diagram.draw(figsize=(8,3), fontsize=12)

print("\\n[2] Applying Rewriting Rules (Normalizing diagrams)...")
from lambeq import Rewriter
rewriter = Rewriter(['prepositional_phrase', 'single_rule'])
rewrite_diagram = rewriter(diagram)
rewrite_diagram.draw(figsize=(8,3), fontsize=12)

print("\\n[3] Converting DisCoCat String Diagram to Quantum Circuit (Ansatz)...")
# We use Instantaneous Quantum Polynomial (IQP) Ansatz, famous for reaching quantum supremacy
ansatz = IQPAnsatz({
    diagram.boxes[0].cod: 1, # Noun type (1 qubit)
    diagram.boxes[1].cod: 1  # Sentence type (1 qubit)
}, n_layers=1, n_single_qubit_params=3)

circuit = ansatz(rewrite_diagram)
circuit.draw(figsize=(8,4), fontsize=12)

print("\\n[4] Rendering Pytket Circuit...")
tket_circuit = circuit.to_tk()
print(f"Circuit requires {tket_circuit.n_qubits} qubits and {tket_circuit.n_gates} gates.")

# NOTE: For physical hardware or rigorous simulations, you can supply your datasets 
# and train this circuit using QuantumTrainer and SPSAOptimizer.
# -------------------------------------------------------------
# trainer = QuantumTrainer(
#     ansatz=ansatz,
#     optimizer=SPSAOptimizer,
#     backend=AerBackend(),
#     epochs=50
# )
# trainer.fit(train_dataset)
`
}
